"""
Smoke tests: send a synthetic image to the model and verify the response
contains the three required section concepts in the selected language.

Run with: python -m pytest tests/ -v
Requires Ollama running locally with gemma4:e4b pulled (USE_OLLAMA=true),
OR HF_TOKEN set (USE_OLLAMA=false).
"""
import sys
import os
from collections.abc import Generator

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from PIL import Image, ImageDraw

from model import run_inference
from utils import contains_devanagari


def _make_test_image() -> Image.Image:
    """Create a simple synthetic 128x128 RGB image (red square on white)."""
    img = Image.new("RGB", (128, 128), color="white")
    draw = ImageDraw.Draw(img)
    draw.rectangle([32, 32, 96, 96], fill="red")
    return img


def _collect(result) -> str:
    """Consume a generator or return a string as-is."""
    if isinstance(result, Generator):
        chunks = list(result)
        return chunks[-1] if chunks else ""
    return result


def test_inference_returns_devanagari():
    """Marathi response must be a non-empty string containing Devanagari."""
    image = _make_test_image()
    result = _collect(run_inference(image, symptom_text="", language="Marathi"))

    assert isinstance(result, str), "Response must be a string"
    assert len(result) > 0, "Response must not be empty"
    assert contains_devanagari(result), (
        f"Response must contain Devanagari text.\nGot: {result!r}"
    )


def test_inference_with_symptom_text():
    """Response with symptom text must still contain Devanagari."""
    image = _make_test_image()
    result = _collect(run_inference(image, symptom_text="रुग्णाला ताप आहे", language="Marathi"))

    assert contains_devanagari(result), (
        f"Response with symptom text must contain Devanagari.\nGot: {result!r}"
    )


def test_response_has_three_sections():
    """
    Response must contain all three section types (detected by keywords).
    Exact header text is generated by the model so we check for key concepts.
    """
    image = _make_test_image()
    result = _collect(run_inference(image, symptom_text="", language="Marathi"))

    # Model should produce output — if Marathi requested, Devanagari must appear
    assert contains_devanagari(result), (
        f"Response must contain Devanagari text.\nFull response: {result!r}"
    )
    assert len(result) > 50, f"Response too short to contain 3 sections: {result!r}"
